### ISSUE TITLE
Implement dark mode

### ISSUE THREAD

**Issue by IanWold** [IanWold/PlanningPoker#6]
There's already [some code for dark mode](https://github.com/IanWold/PlanningPoker/blob/main/PlanningPoker.Client/wwwroot/index.html#L44) to automatically set dark mode if the user's system is set to use dark mode by default, but that's commented since Bootstrap's dark mode does not invert [bg-light](https://github.com/IanWold/PlanningPoker/blob/main/PlanningPoker.Client/wwwroot/index.html#L25). This should be fixed on our end, then this code should be uncommented.

**Comment by Tortoise247** [comment]
Hi, @IanWold 

May I tackle this issue?

 I'm a beginner so please advise if I'm doing something wrong.

**Comment by IanWold** [comment]
Hi @Tortoise247, you certainly may take a crack at it!

You'll see that the commented-out JavaScript I linked will add the attribute `data-bs-theme="dark"` to the document element. This triggers Bootstrap to put everything in dark mode. Bootstrap's documentation on that is here: https://getbootstrap.com/docs/5.3/customize/color-modes/

What you can do through testing is to put that attribute on the `body` or the `div id="app"` in order to set it to dark mode. You'll see most things working but other things need a little massaging in HTML or CSS.

Have fun with it, I'll be happy to answer any questions :)
